---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: slinky-slurm-controlplane
spec:
  chartRef:
    kind: OCIRepository
    name: slinky-slurm
  valuesFrom:
    - kind: ConfigMap
      name: slinky-slurm-defaults
      valuesKey: values.yaml
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  driftDetection:
    mode: enabled
  interval: 10m
  timeout: 10m
