---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: jupyterhub
spec:
  chartRef:
    kind: HelmChart
    name: jupyterhub
  releaseName: jupyterhub
  valuesFrom:
  - kind: ConfigMap
    name: jupyterhub-config
  # - kind: Secret
  #   name: jupyterhub-keycloak-config
  #   valuesKey: keycloakClientSecret
  #   targetPath: hub.config.GenericOAuthenticator.client_secret
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  interval: 5m
  postRenderers:
  - kustomize:
      patches:
        - target:
            kind: Deployment
            name: .*
          patch: |-
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: set-run-as-non-root
            spec:
              template:
                spec:
                  securityContext:
                    runAsNonRoot: true
                    seccompProfile:
                      type: RuntimeDefault
        - target:
            kind: StatefulSet
            name: .*
          patch: |-
            apiVersion: apps/v1
            kind: StatefulSet
            metadata:
              name: set-run-as-non-root
            spec:
              template:
                spec:
                  securityContext:
                    runAsNonRoot: true
                    seccompProfile:
                      type: RuntimeDefault
