---
namespace: kubescape

configMapGenerator:
  - name: kubescape-defaults
    files:
      - values.yaml=defaults.yaml

configurations:
  - kustomizeconfig.yaml

resources:
  - helmrepository.yaml
  - helmrelease.yaml
  - namespace.yaml