apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keda
  namespace: flux-system
spec:
  interval: 5m
  path: "./apps/keda/"
  sourceRef:
    kind: GitRepository
    name: myapps
  prune: true
