---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: tetragon
spec:
  chart: tetragon
  version: "v1.3.0"
  sourceRef:
    kind: HelmRepository
    name: tetragon
  interval: 10m0s
