---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tetragon
spec:
  chartRef:
    kind: HelmChart
    name: tetragon
  releaseName: tetragon
  valuesFrom:
  - kind: ConfigMap
    name: tetragon
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  interval: 5m
